# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='digest',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
